# Basic dependabot.yml file with
# minimum configuration for two package managers of annotator

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"

  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"

- package-ecosystem: "docker"
    directory: "/.vscode"
    schedule:
      interval: "weekly"
    target-branch: "development"
